### ISSUE TITLE
Mongodb issue 

### ISSUE THREAD

**Issue by DevanshiNigam** [rammohanmishra/DOAuth#1]
//error in the insert command(line 27) :The method insert(DBObject[]) in the type DBCollection is not applicable for the arguments (BasicDBObject)

package demo;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;
import com.mongodb.WriteConcern;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.BasicDBObject;
import com.mongodb.DBObject;
import com.mongodb.DBCursor;
import com.mongodb.ServerAddress;
import java.util.Arrays;

public class MongoDBJDBC{
   public static void main( String args[] ){
      try{   
		
         MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
         
         DB db = mongoClient.getDB( "newdb" );
		 System.out.println("Connect to database successfully");
		 DBCollection coll = db.createCollection("first", null);
         System.out.println("Collection created successfully");
        DBCollection col = db.getCollection("first");
         System.out.println("Collection mycol selected successfully");
         BasicDBObject doc = new BasicDBObject("title", "MongoDB").
                 append("description", "database");
                 coll.insert(doc);
              System.out.println("Document inserted successfully");
      }catch(Exception e){
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );
	  }
   }
}

**Comment by rammohanmishra** [comment]
Object of insert() method is wrong. You are trying to insert in Collection which you got after create.

Try to use Collection which you got after after getCollection() i.e "col".
